# Description: This script reads and processes the output file generated by the TM-align program,
#              extracting protein pair comparisons and their corresponding TM scores.

import pandas as pd

def process_tm_align_output():
    """
    Read and process the output file of the TM-align program.
    
    Returns:
    dataframe (pandas.DataFrame): A dataframe containing the protein pair comparisons and TM scores.
    """
    # Specify the path to the output file
    filename = '../output.txt'
    
    # Open the output file for reading
    output_file = open(filename, 'r')
    
    # Initialize lists to store the extracted data
    protein_left = []
    protein_right = []
    tm_score_left = []
    tm_score_right = []
  
    # Iterate through each line in the output file
    for line in output_file:
        # Split the line into individual fields
        fields = line.split()
        
        # Extract protein names and TM scores
        protein_left.append(fields[0])
        protein_right.append(fields[1])
        tm_score_left.append(fields[2])
        tm_score_right.append(fields[3])
    
    # Close the output file
    output_file.close()
    
    # Remove header and footer entries from the extracted lists
    protein_left.pop(0)
    protein_right.pop(0)
    tm_score_left.pop(0)
    tm_score_right.pop(0)
    protein_left.pop(len(protein_left)-1)
    protein_right.pop(len(protein_right)-1)
    tm_score_left.pop(len(tm_score_left)-1)
    tm_score_right.pop(len(tm_score_right)-1)
  
    # Create a pandas DataFrame from the extracted data
    dataframe = pd.DataFrame(
        list(zip(protein_left, protein_right, tm_score_left, tm_score_right)),
        columns=['Protein 1', 'Protein 2', 'TM Score 1', 'TM Score 2']
    )
    
    # Convert TM Score columns to numeric data type
    dataframe['TM Score 1'] = pd.to_numeric(dataframe['TM Score 1'])
    dataframe['TM Score 2'] = pd.to_numeric(dataframe['TM Score 2'])
    
    return dataframe


if __name__ == '__main__':
    # Process the TM-align output file
    tm_scores_dataframe = process_tm_align_output()
    
    # Print the total number of comparisons
    print("In total there are %d comparisons" % tm_scores_dataframe.shape[0])
    
    # Save the dataframe as a CSV file if 'save' flag is True
    save = True
    if save:
        tm_scores_dataframe.to_csv('../TM_scores.csv', index=False)
